language: python
python:
    - "2.7"
install:
    - pip install -e . --use-mirrors
before_script:
    - pip install coverage coveralls --use-mirrors
script:
    - nosetests --with-coverage --cover-package=il2ds_log_parser
after_success:
    - coveralls
